# checklist_data.py

sections = [
    ("4 Weeks Before Moving", [
        "Book professional removalists or a moving truck.",
        "Notify landlord or real estate agent if renting.",
        "Declutter: donate, sell, or dispose of unwanted items.",
        "Arrange care or transport for pets and children on moving day.",
        "Back up important files and documents.",
        "Order packing supplies: boxes, tape, bubble wrap, markers.",
        "Update or arrange home and contents insurance.",
        "Schedule utility disconnection at your old address and connection at your new address.",
        "Set up mail redirection with your postal service.",
        "Create a household inventory, especially for valuable items.",
    ]),
    ("3 Weeks Before Moving", [
        "Start packing non-essential items (books, decor, out-of-season clothes).",
        "Notify relevant organisations of your change of address (banks, insurance, government, subscriptions, employer, medical providers, friends/family).",
        "Prepare a moving kit for pets (food, bowls, bedding, toys, medications).",
        "Book professional cleaning for your old home if required.",
        "Pack non-essential office or work-from-home equipment.",
        "Cancel or transfer regular services (cleaner, gardener, pool maintenance).",
    ]),
    ("2 Weeks Before Moving", [
        "Continue packing, focusing on less-used rooms and items.",
        "Use up food from the fridge, freezer, and pantry.",
        "Confirm utility disconnection/connection dates and arrange for final meter readings.",
        "Confirm moving date, time, and access/parking with removalists.",
        "Confirm arrangements for pets and children on moving day.",
        "Photograph cable setups for electronics for easy reassembly.",
    ]),
    ("1 Week Before Moving", [
        "Pack most remaining items, leaving out essentials for the final days.",
        "Disassemble large furniture (beds, tables, shelving).",
        "Prepare appliances: defrost fridge/freezer, empty washing machine, clean oven.",
        "Pack an essentials box (kettle, snacks, plates, cutlery, cleaning supplies, toilet paper, towels, bed linen, pet food, office essentials).",
        "Set aside important documents, jewellery, and electronics to transport yourself.",
        "Arrange final inspection with landlord/agent if renting.",
        "Plan furniture layout for your new home.",
        "Prepare a secure room or crate for pets on moving day.",
    ]),
    ("Day Before Moving", [
        "Pack overnight bags for each person and pet (clothes, toiletries, medications, chargers, pet food, leads, litter tray).",
        "Charge all phones, laptops, and tablets.",
        "Clean fridge/freezer and leave doors open to prevent mould.",
        "Take photos of gas, electricity, and water meters.",
        "Inspect all rooms, cupboards, garage, and shed for forgotten items.",
        "Collect all keys and manuals for handover.",
        "Leave a forwarding address for the new occupants.",
    ]),
    ("Moving Day", [
        "Keep pets and children in a secure, quiet room or with a sitter.",
        "Direct removalists as needed, especially for fragile or valuable items.",
        "Do a final walkthrough to check all areas are empty and clean.",
        "Turn off water, gas, electricity, and hot water system.",
        "Hand over keys to agent or new owner.",
        "At your new home, check utilities are working and do a quick clean if needed.",
        "Unpack essentials: beds, kitchen, bathroom, pet area, and work-from-home setup.",
    ]),
    ("After the Move", [
        "Unpack room by room, starting with bedrooms and kitchen.",
        "Check for any damage or missing items and notify removalists if needed.",
        "Update your address with any missed organisations.",
        "Register with local GP, dentist, and update pet microchip details if needed.",
        "Set up regular services at your new home (cleaner, gardener, pool maintenance).",
        "Dispose of packing materials responsibly.",
        "Relax and enjoy your new home!",
    ]),
]
